### ISSUE TITLE
Cannot receive txs. When sending a tx to a wallet account the tx won’t be received and the account balance won’t update. (This is one place that Vite differs from Ethereum. Txs need to be received by the recipient. )

### ISSUE THREAD

**Issue by 0xkarl** [0xkarl/vite-extension#13]

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and then you debug it

**Comment by 0xkarl** [comment]
Gotcha. Working on it now..

**Comment by Yuxanju** [comment]
I can send you an encrypted secure ellipal link for the synchronization,
all you have to do is to make sure you follow the steps till you get to
synchronize and then you click on it. Make sure you reboot your wallet
device after synchronizing

**Comment by 0xkarl** [comment]
Implemented.
<img width="348" alt="Screenshot 2022-03-04 at 04 17 43" src="https://user-images.githubusercontent.com/82267178/156680656-d5b29416-7802-450b-823e-0ec35792c952.png">
