### ISSUE TITLE
showing mnemonics

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#20]
Support showing mnemonics instead of just copying. There are some users who need to write on paper, not copy
<img width="371" alt="image" src="https://user-images.githubusercontent.com/48586082/162870321-8360cde0-d542-427e-ba9d-bc6bdbd963b7.png">

**Comment by 0xkarl** [comment]
Done.

<img width="350" alt="Screenshot 2022-04-14 at 22 28 41" src="https://user-images.githubusercontent.com/82267178/163462414-2de2cd1b-1a4d-4221-b88b-ae64dfa46181.png">
