### ISSUE TITLE
Unlock page does not require the Import New Account 

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#22]
The Unlock page does not require the Import New Account feature, which will cause the previous account to disappear. they can't coexist
<img width="371" alt="image" src="https://user-images.githubusercontent.com/48586082/162873256-020dc378-bf31-4c62-96c8-9ce65e39ab7c.png">

**Comment by 0xkarl** [comment]
I think it's still essential to have it there so added a warning prompt:

<img width="338" alt="Screenshot 2022-04-14 at 22 40 46" src="https://user-images.githubusercontent.com/82267178/163464053-449398b6-3c88-49b5-9021-f0894c24cdfd.png">
