### ISSUE TITLE
Automatic receive

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#24]
Automatic receive, no need to click manually.
Before there is no receive, unreceive transactions can still be displayed, just like now

<img width="371" alt="image" src="https://user-images.githubusercontent.com/48586082/162900757-e99bb521-2f4b-4a6c-8f89-b9b0b7cf1b26.png">

**Comment by 0xkarl** [comment]
I'll add a setting flag, a user can toggle to auto-receive txns.

**Comment by 0xkarl** [comment]
Incoming blocks are now auto-received on boot.
