### ISSUE TITLE
open SDK

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#25]
Is it possible to have an open SDK so that Dapps such as VIVA, vitepunk, vitebridge can use extension to log in and sign

**Comment by 0xkarl** [comment]
This actually exists and is documented here https://0xkarl.github.io/vite-extension/features/injected-script.html. Basically uses the same API as Metamask's. You cna try this out in this [sample dapp](https://vite-extension.surge.sh/example.html). Also, checkout this [video demo](https://www.youtube.com/watch?v=JmufcGt_pic&feature=youtu.be).
