### ISSUE TITLE
transaction records 

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#26]
Is it possible to put transaction records under each token, like metamask

<img width="371" alt="image" src="https://user-images.githubusercontent.com/48586082/162902796-5264ed1a-d8de-469d-aec7-a1d8da198461.png">

**Comment by 0xkarl** [comment]
Initialized the dedicated token page containing its txs:

<img width="302" alt="Screenshot 2022-04-15 at 01 19 11" src="https://user-images.githubusercontent.com/82267178/163486301-0b6d2c63-6287-443e-8d29-4f949a173d6a.png">

<img width="370" alt="Screenshot 2022-04-15 at 01 18 45" src="https://user-images.githubusercontent.com/82267178/163486372-621de09b-f5f7-4a6c-9484-dda3d4bffad3.png">
