### ISSUE TITLE
Asset & Activities

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#30]
This part of the spacing can be increased. or other ways.

At present, it seems that the text describes the icon above. No text displayed can be clicked

<img width="394" alt="image" src="https://user-images.githubusercontent.com/48586082/163946836-393cfb47-59fc-4c53-9c1f-2078322f951a.png">

**Comment by 0xkarl** [comment]
Added labels to be more descriptive.

**Comment by 0xkarl** [comment]
Fixed.
