### ISSUE TITLE
connect dapp

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#31]
The signature pop-up window is best on the right side of the screen

The demo test was unsuccessful. https://vite-extension.surge.sh/example.html

It is best to see the linked dapp in the wallet, and users can disconnect the dapp

<img width="803" alt="image" src="https://user-images.githubusercontent.com/48586082/163947336-77663378-08ef-456e-8010-a6597bd182fe.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/48586082/163947397-d84d176b-2759-4714-98a3-980ca446d75b.png">

**Comment by 0xkarl** [comment]
Please switch to testnet in the extension because of quota.
