### ISSUE TITLE
transaction record style

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-extension#32]
The transaction record style, it is best to be consistent, use the received style of the newline.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/48586082/163949990-0c0d88cc-180a-4e03-bc02-fa744db41d8e.png">

<img width="353" alt="image" src="https://user-images.githubusercontent.com/48586082/163949781-21120ef6-2f10-4342-a6d6-75697abfe8b7.png">

**Comment by 0xkarl** [comment]
Fixed.
